<%
require 'yaml'
formula = YAML.load_file('FORMULA')
formula_name = formula['name']
%>
---
verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  salt_pillar_root: pillar.example
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: <%= formula_name %>
  state_top:
    base:
      '*':
        - <%= formula_name %>

suites:
  - name: default
